### ISSUE TITLE
Assignment instead of condition in src/DRgui_impl.cpp

### ISSUE THREAD

**Issue by Yup746** [Rasbats/DR_pi#10]
On line 123 in src/DRgui_impl.cpp there is an assignment in the if statement instead of a condition. Here's a heads-up if it was not meant to be like that.

**Comment by Rasbats** [comment]
Thanks. Appreciated.

**Comment by Rasbats** [comment]
TODO.

**Comment by Rasbats** [comment]
Thanks. Appreciated. TODO
