### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by mschiff** [Rasbats/DR_pi#3]
Dear developer,

I would like to make your plugin available to the users of Gentoo Linux.

Right now this is not possible because there are no releases available for your plugin.

It would be very usefull to have tagged releases, so the source for a specific version of the plugin can be downloaded. Please add a release/tag for your released versions. This makes packaging a lot easier.

Please see: [Creating Releases](https://help.github.com/articles/creating-releases/)

Thanks in advance!

**Comment by Rasbats** [comment]
New release has been made from the master of DR_pi. Please can you test that the code from the zip file compiles correctly on Linux.

**Comment by mschiff** [comment]
Looks good to me, thanks! Just a little note: Please use a consistent tagging scheme. This time my automatic build fails because you used an uppercase 'V' for the version tag, not a lowercase one. If this kept the same, packaging work is much less for me. Thank you!
